name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install, build
      run: |
        yarn install
        yarn workspace @uwu/client run compile
        yarn workspace @uwu/client run package --release never
